steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/martian', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/martian']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'martian', '--image', 'gcr.io/$PROJECT_ID/martian', '--region', 'us-central1']
images:
  - 'gcr.io/$PROJECT_ID/martian'
